### ISSUE TITLE
сместить стрелки как в дизайне

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [nicolaypetrovich/rocket-valemi#40]
http://prntscr.com/l4eufo

**Comment by VladyslavKovalchuk** [comment]
поправить в моб и планшетной
http://prntscr.com/l57lzf
http://prntscr.com/l57m5o
дизайн: http://prntscr.com/l57mbg
http://prntscr.com/l57mj2

**Comment by Derevyanchenko** [comment]
подвинул
(А вообще это елемент дизайна)
